language: php

php:
  - 7.0
  - 7.1

env:
  - COMPOSER_FLAGS="--prefer-lowest"
  - COMPOSER_FLAGS=""

matrix:
  exclude:
    - php: 7.1
      env: COMPOSER_FLAGS="--prefer-lowest"

sudo: false

cache:
  directories:
    - $HOME/.composer/cache

before_script:
  - travis_retry composer self-update
  - travis_wait composer update ${COMPOSER_FLAGS} --no-interaction --prefer-stable

script:
  - vendor/bin/phpunit

notifications:
  email: false
